### ISSUE TITLE
ERROR Alephium.app.Boot$

### ISSUE THREAD

**Issue by Good2Myself** [alephium/gpu-miner#60]
> [33m2024-04-11 12:37:22,745[0;39m [32m[main][0;39m          [1;31mERROR[0;39m [36mo.alephium.app.Boot$[0;39m                   - Cannot initialize system: {}
org.rocksdb.RocksDBException: Failed to create lock file: C:\Users\h\.alephium\mainnet\db/LOCK: The process cannot access the file because it is being used by another process.

	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:306)
	at org.alephium.io.RocksDBSource$.openUnsafeWithOptions(RocksDBSource.scala:176)
	at org.alephium.io.RocksDBSource$.openUnsafe(RocksDBSource.scala:156)
	at org.alephium.flow.io.Storages$.createRocksDBUnsafe(Storages.scala:92)
	at org.alephium.flow.io.Storages$.createUnsafe(Storages.scala:46)
	at org.alephium.app.Server$Impl.<init>(Server.scala:123)
	at org.alephium.app.Server$.apply(Server.scala:105)
	at org.alephium.app.BootUp.<init>(Boot.scala:58)
	at org.alephium.app.Boot$.delayedEndpoint$org$alephium$app$Boot$1(Boot.scala:37)
	at org.alephium.app.Boot$delayedInit$body.apply(Boot.scala:35)
	at scala.Function0.apply$mcV$sp(Function0.scala:42)
	at scala.Function0.apply$mcV$sp$(Function0.scala:42)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:98)
	at scala.App.$anonfun$main$1$adapted(App.scala:98)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at scala.App.main(App.scala:98)
	at scala.App.main$(App.scala:96)
	at org.alephium.app.Boot$.main(Boot.scala:35)
	at org.alephium.app.Boot.main(Boot.scala)

>

**Comment by tdroxler** [comment]
>The process cannot access the file because it is being used by another process.

You might have another instance of the node running, try to kill all your java processes and restart

**Comment by Good2Myself** [comment]
I can't find it in task manager or open windows, could it be - Wowlet or Wownerod?
